### PR TITLE
Updated START tagging ADM

### PR DESCRIPTION
**Pull request by eveenhuis**
- Modified prompt
- Removed duplicated RED tag example, replaced with missing BLACK tag example
- Removed duplicated inference call in `identify_tag_color`

### CODE REVIEW

**Comment by dmjoy** [comment]
@eveenhuis no issue here with the proposed changes.  Though please update the `CHANGELOG.md` file, if there isn't one already I typically create a new section above the latest release called `Unreleased` to track the changes prior to cutting an actual release, e.g.:
```
## Unreleased

### Added
- Added something

### Changed

### Fixed
- Fixed something

```

**Comment by dmjoy** [comment]
Slightly longer term it is worth thinking about capturing this prompt and samples somewhere alongside the other templates/texts so that we can switch between them more easily if we ever need to (for a/b testing etc.)

**Comment by eveenhuis** [comment]
@dmjoy Added the changelog entry

Completely agree about the templating, Bill already has that as a TODO in the code. It doesn't look like we really use issues in this repo, is there somewhere specific we should note that down?

**Comment by dmjoy** [comment]
Thanks for the update, merging shortly.

We haven't historically used the issues here, but seems like a good time to start (especially since this is a very code specific task).

**Pull request merged**
